INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Google',3412,'Fusce mi lorem, vehicula et, rutrum eu, ultrices sit','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',10541,'mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Apple',19403,'nunc. In at pede. Cras vulputate velit eu','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Finale',27690,'porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',14937,'malesuada fames ac turpis egestas. Fusce aliquet magna','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Yahoo',14032,'sed turpis nec mauris blandit mattis. Cras eget','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',26289,'viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',35491,'sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',45678,'mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut,','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Finale',33741,'metus vitae velit egestas lacinia. Sed congue, elit','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES ('Google',25435,'adipiscing, enim mi tempor lorem, eget mollis lectus pede','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',32125,'semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Borland',43566,'Pellentesque habitant morbi tristique senectus et netus et','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Borland',17744,'enim nisl elementum purus, accumsan interdum libero dui','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',44569,'parturient montes, nascetur ridiculus mus. Proin vel','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',47426,'Donec nibh enim, gravida sit amet, dapibus id,','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',16725,'litora torquent per conubia nostra, per inceptos hymenaeos. Mauris','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Borland',8789,'nostra, per inceptos hymenaeos. Mauris ut quam vel sapien','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Borland',8809,'In nec orci. Donec nibh. Quisque nonummy','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',28432,'libero lacus, varius et, euismod et, commodo at, libero.','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES ('Finale',41335,'dui augue eu tellus. Phasellus elit pede, malesuada','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',10096,'egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae,','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Finale',26293,'et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',45821,'nec mauris blandit mattis. Cras eget nisi dictum augue','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Cakewalk',24283,'Aliquam adipiscing lobortis risus. In mi pede, nonummy ut,','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',3054,'ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Microsoft',36719,'varius et, euismod et, commodo at, libero. Morbi','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',29088,'primis in faucibus orci luctus et ultrices posuere cubilia','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',5750,'purus, in molestie tortor nibh sit amet','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',14860,'vestibulum, neque sed dictum eleifend, nunc risus varius orci, in','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria)VALUES ('Borland',29580,'arcu. Vestibulum ante ipsum primis in faucibus orci','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',14974,'viverra. Donec tempus, lorem fringilla ornare placerat,','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',44145,'Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit,','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',15827,'non enim commodo hendrerit. Donec porttitor tellus non','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Finale',30197,'Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus,','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Apple',45579,'metus sit amet ante. Vivamus non lorem','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Apple',43124,'scelerisque dui. Suspendisse ac metus vitae velit','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',44913,'facilisi. Sed neque. Sed eget lacus. Mauris non dui nec','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',29628,'netus et malesuada fames ac turpis egestas. Fusce aliquet','Bebestible');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Microsoft',15891,'elit, pretium et, rutrum non, hendrerit id, ante. Nunc','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',24207,'pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',49385,'luctus. Curabitur egestas nunc sed libero. Proin','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Apple',36753,'tristique pellentesque, tellus sem mollis dui, in sodales elit','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Microsoft',32721,'arcu ac orci. Ut semper pretium neque. Morbi','Bebestible');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Microsoft',48659,'blandit mattis. Cras eget nisi dictum augue malesuada malesuada.','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',7298,'conubia nostra, per inceptos hymenaeos. Mauris ut','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',36285,'suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',28518,'auctor non, feugiat nec, diam. Duis mi','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Cakewalk',21855,'tempus eu, ligula. Aenean euismod mauris eu elit. Nulla','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Finale',26655,'Curabitur ut odio vel est tempor bibendum. Donec felis','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',9591,'metus sit amet ante. Vivamus non lorem vitae odio sagittis','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',9955,'Nulla semper tellus id nunc interdum feugiat. Sed','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Google',14415,'tincidunt tempus risus. Donec egestas. Duis ac arcu.','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Microsoft',45417,'felis orci, adipiscing non, luctus sit amet, faucibus ut,','Bebestible');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',33943,'eget varius ultrices, mauris ipsum porta elit, a feugiat','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Borland',2730,'risus. Morbi metus. Vivamus euismod urna. Nullam lobortis','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',15701,'dui quis accumsan convallis, ante lectus convallis','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Yahoo',23401,'tellus sem mollis dui, in sodales elit erat','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',24059,'Mauris nulla. Integer urna. Vivamus molestie dapibus ligula.','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Microsoft',11700,'facilisis, magna tellus faucibus leo, in lobortis tellus justo sit','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES  ('Borland',34364,'vitae dolor. Donec fringilla. Donec feugiat metus sit amet','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Cakewalk',26617,'Proin vel arcu eu odio tristique pharetra. Quisque ac','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',33759,'ac turpis egestas. Fusce aliquet magna a neque. Nullam ut','Bebestible');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Google',36020,'Quisque libero lacus, varius et, euismod et, commodo at,','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Cakewalk',20114,'ante ipsum primis in faucibus orci luctus et ultrices','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Borland',3326,'et malesuada fames ac turpis egestas. Fusce aliquet','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',12417,'odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',18070,'ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula.','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',23229,'vel arcu eu odio tristique pharetra. Quisque ac libero','Maquinaria');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Apple',36651,'habitant morbi tristique senectus et netus et','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES ('Cakewalk',23064,'in lobortis tellus justo sit amet nulla. Donec non justo.','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',38671,'lorem, vehicula et, rutrum eu, ultrices sit amet,','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',25460,'Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',4676,'elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Cakewalk',45003,'a, arcu. Sed et libero. Proin mi. Aliquam','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',18708,'malesuada. Integer id magna et ipsum cursus vestibulum. Mauris','Bebestible');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',27783,'Nam ligula elit, pretium et, rutrum non, hendrerit id,','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Yahoo',12033,'urna, nec luctus felis purus ac tellus. Suspendisse sed','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Borland',33400,'semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim','Bebestible');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Borland',23017,'eu dolor egestas rhoncus. Proin nisl sem, consequat','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',8602,'Duis risus odio, auctor vitae, aliquet nec, imperdiet','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',19229,'Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Finale',25292,'pretium aliquet, metus urna convallis erat, eget tincidunt','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Microsoft',9288,'luctus felis purus ac tellus. Suspendisse sed dolor. Fusce','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Finale',4091,'dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare,','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',41718,'vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',35186,'posuere at, velit. Cras lorem lorem, luctus ut, pellentesque','Comida');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Yahoo',31172,'mus. Donec dignissim magna a tortor. Nunc commodo auctor','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Sibelius',7043,'tellus. Aenean egestas hendrerit neque. In ornare sagittis','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Google',26304,'sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam','Bebestible');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES ('Finale',18427,'sem ut dolor dapibus gravida. Aliquam tincidunt, nunc','Bebestible');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Amazon',9960,'scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est.','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Adobe',19616,'adipiscing lobortis risus. In mi pede, nonummy ut, molestie in,','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',17621,'Cum sociis natoque penatibus et magnis dis parturient','Tecnologia');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Yahoo',15996,'a, magna. Lorem ipsum dolor sit amet, consectetuer','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Yahoo',39243,'lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet','Viaje');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',3395,'fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque','Limpieza');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Yahoo',9755,'Vivamus non lorem vitae odio sagittis semper. Nam','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Chami',9073,'interdum feugiat. Sed nec metus facilisis lorem tristique','Arte');
INSERT INTO productos (nombre,precio,caracteristicas,categoria) VALUES('Lavasoft',46993,'elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum.','Bebestible');
